### Numpy는 내부적으로 데이터를 다른 내장 파이썬 객체와 구분된 연속된 메모리 블록에 저장합니다.
- 파이썬의 연속된 자료형들보다 훨씬 더 적은 메모리를 사용
- Numpy연산은 파이썬 반복문을 사용하지 않고 전체 배열에 대한 복잡한 계산수행 가능

In [2]:
import numpy as np

### NumPy 가 훨씬 빠르다

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [7]:
%time for i in range(10): my_arr * 2

CPU times: user 22.3 ms, sys: 11 ms, total: 33.3 ms
Wall time: 32.9 ms


In [8]:
%time for i in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 695 ms, sys: 189 ms, total: 884 ms
Wall time: 889 ms


### 4.1 Ndarray 
- N차원의 배열 객체
- 대규모 데이터 집합을 담을 수 있는 빠르고 유연한 자료구조

#### 4.1.1 ndarray 생성

In [3]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [4]:
data2 = [[1, 2, 3,4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
arr2.ndim, arr2.shape

(2, (2, 4))

In [7]:
np.zeros(10), np.ones(10)

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))

In [8]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
np.empty((2,3,2))

array([[[0.0e+000, 0.0e+000],
        [3.5e-323, 0.0e+000],
        [0.0e+000, 0.0e+000]],

       [[0.0e+000, 0.0e+000],
        [0.0e+000, 0.0e+000],
        [0.0e+000, 0.0e+000]]])

In [ ]:
# zeros는 메모리를 할당하여 새로운 배열을 생성하지만, ones or zeros처럼 값을 초기화 하지 않는다.

#### 4.1.2 자료구조 변경

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [12]:
float_arr = arr.astype(np.float)
float_arr.dtype

In [14]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype = np.float64)

In [16]:
#다른 배열의 dtype속성을 이용해서 속성바꾸기도 가능
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 4.1.3 NumPy 배열의 산술 연산

In [17]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [24]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [25]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [27]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [28]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [29]:
arr > arr2

array([[ True, False,  True],
       [False,  True, False]])

In [30]:
#### 4.1.4 색인과 슬라이싱 기초

arr = np.arange(10)

In [31]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr[5:8]

array([5, 6, 7])

In [34]:
arr[5:8] = 12 

In [35]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [36]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [38]:
arr_slice[1] = 12345

In [39]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [ ]:
#arr[5:8].copy() 를 통해 복사본을 얻어 변하지 않게 하는것이 가능하다.

In [44]:
arr2d = np.arange(1,10)

In [46]:
arr2d = arr2d.reshape(3,3)

In [50]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

#### 4.1.5 불리언값으로 선택하기

In [55]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])

In [56]:
data = np.random.randn(7,4)

In [59]:
data

array([[ 0.04692173,  1.39406114, -0.01065472,  0.43898516],
       [-0.46828234,  1.63828402,  0.86527354, -1.37414083],
       [ 0.96233484, -0.15051886, -1.39953866,  1.38531367],
       [ 0.83423724, -0.1060396 ,  0.18378385, -1.09926074],
       [-1.18384335,  0.47750359, -0.50150528, -1.11524394],
       [-1.07314678,  0.94080917, -0.95491214,  0.05895853],
       [ 0.50050744,  0.82824345, -1.24027531,  1.25233947]])

In [58]:
data[names == "Bob"]

array([[ 0.04692173,  1.39406114, -0.01065472,  0.43898516],
       [ 0.83423724, -0.1060396 ,  0.18378385, -1.09926074]])

In [62]:
cond = names == "Bob"

In [63]:
# ~연산자는 반대조건을 ㅏ타낼때 쓴다.
data[~cond]

array([[-0.46828234,  1.63828402,  0.86527354, -1.37414083],
       [ 0.96233484, -0.15051886, -1.39953866,  1.38531367],
       [-1.18384335,  0.47750359, -0.50150528, -1.11524394],
       [-1.07314678,  0.94080917, -0.95491214,  0.05895853],
       [ 0.50050744,  0.82824345, -1.24027531,  1.25233947]])

#### 4.1.6 팬시색인

In [75]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i

In [65]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [67]:
#특정한 순서를 선택하고 싶으면, 이렇게 리스트를 넘기면 된다
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [68]:
# 다차원은 조금 다르다.
arr = np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [70]:
# 1 row의 0번 column, 5 row의 3번 column 등등 (0번부터 시작)
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [74]:
# 이런식도 가능하다
arr[[1, 5, 7, 2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

#### 4.1.7 배열 전치와 축 바꾸기

In [76]:
arr = np.arange(15).reshape(3, 5)

In [77]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [78]:
#transpose 기능
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [80]:
# 행렬의 내적은 주로 np.dot을 이용해서 구할 수 있다.
np.dot(arr.T, arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [81]:
np.dot(arr, arr.T)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [98]:
arr = np.arange(16).reshape(2,2,4)

In [84]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [99]:
a = np.arange(1, 13)
aaa = a.reshape(2,2,3)
aaa

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### aaa 모양

<img src="./imgs/4_1.png" width="40%">

In [108]:
aaa.transpose(0,1,2)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [86]:
# 다차원 배열의 경우 transpose 메서드는 튜플로 축 번호를 받아서 치환한다.
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [109]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [96]:
arr.transpose((2, 0,1))

array([[[ 0,  4],
        [ 8, 12]],

       [[ 1,  5],
        [ 9, 13]],

       [[ 2,  6],
        [10, 14]],

       [[ 3,  7],
        [11, 15]]])

In [110]:
#swapaxes 라는 메서드를 통해 두개의 축 번호를 받아 배열을 바꾸기도함
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [111]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

#### 4.2 유니버설 함수: 배열의 각 원소를 빠르게 처리하는 함수

In [112]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [114]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [115]:
x = np.random.randn(8)
y = np.random.randn(8)

In [116]:
x, y


(array([ 0.03392903,  1.55870744, -1.55828234, -0.33267941,  0.86113321,
         1.35586774,  0.07909043, -0.00370638]),
 array([-0.64506255, -0.55128778,  0.23418489,  0.9067162 , -0.55722518,
        -0.62513787,  0.2687008 , -0.36377807]))

In [118]:
# x,y 둘중 큰것을 표기
np.maximum(x, y)

array([ 0.03392903,  1.55870744,  0.23418489,  0.9067162 ,  0.86113321,
        1.35586774,  0.2687008 , -0.00370638])

### 4.3 배열을 이용한 배열지향 프로그래밍

In [126]:
points = np.arange(-5, 5)
xs, ys = np.meshgrid(points, points)

In [127]:
xs

array([[-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4]])

In [128]:
ys

array([[-5, -5, -5, -5, -5, -5, -5, -5, -5, -5],
       [-4, -4, -4, -4, -4, -4, -4, -4, -4, -4],
       [-3, -3, -3, -3, -3, -3, -3, -3, -3, -3],
       [-2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4]])

In [129]:
z = np.sqrt(xs **2 + ys ** 2)

In [130]:
z

array([[7.07106781, 6.40312424, 5.83095189, 5.38516481, 5.09901951,
        5.        , 5.09901951, 5.38516481, 5.83095189, 6.40312424],
       [6.40312424, 5.65685425, 5.        , 4.47213595, 4.12310563,
        4.        , 4.12310563, 4.47213595, 5.        , 5.65685425],
       [5.83095189, 5.        , 4.24264069, 3.60555128, 3.16227766,
        3.        , 3.16227766, 3.60555128, 4.24264069, 5.        ],
       [5.38516481, 4.47213595, 3.60555128, 2.82842712, 2.23606798,
        2.        , 2.23606798, 2.82842712, 3.60555128, 4.47213595],
       [5.09901951, 4.12310563, 3.16227766, 2.23606798, 1.41421356,
        1.        , 1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [5.        , 4.        , 3.        , 2.        , 1.        ,
        0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.09901951, 4.12310563, 3.16227766, 2.23606798, 1.41421356,
        1.        , 1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [5.38516481, 4.47213595, 3.6055512

In [134]:
%matplotlib

Using matplotlib backend: MacOSX


In [131]:
import matplotlib.pyplot as pt

In [ ]:
plt.imshow(z, cmap = plt.cm.gray); plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

#### 4.3.1 배열 연산으로 조건절 표현하기

- numpy.where 함수는 x if 조건 else y 같은 삼항식의 벡터화된 버전

In [3]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [5]:
# cond값이 True일때는 xarr, False이면 yarr일경우
result =[(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [7]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [8]:
arr = np.random.randn(4,4)
arr

array([[ 0.50779564,  0.96245373,  0.79044427, -0.21923379],
       [-1.48556614, -2.55547651,  0.80248933,  1.5960264 ],
       [-1.83161542, -0.52669933, -0.08149903,  0.62981909],
       [ 1.34930465,  0.94390697, -0.21795981,  1.87004388]])

In [9]:
arr>0

array([[ True,  True,  True, False],
       [False, False,  True,  True],
       [False, False, False,  True],
       [ True,  True, False,  True]])

In [13]:
# arr>0 인것은 모두 2로, 반대는 -2로 바꿀 수 있다.
np.where(arr>0, 2, -2)

array([[ 2,  2,  2, -2],
       [-2, -2,  2,  2],
       [-2, -2, -2,  2],
       [ 2,  2, -2,  2]])

In [14]:
# arr>0 인것만 2로, 나머지는 그대로
np.where(arr>0, 2, arr)

array([[ 2.        ,  2.        ,  2.        , -0.21923379],
       [-1.48556614, -2.55547651,  2.        ,  2.        ],
       [-1.83161542, -0.52669933, -0.08149903,  2.        ],
       [ 2.        ,  2.        , -0.21795981,  2.        ]])

In [15]:
#### 4.3.2 수학 메서드와 통계 메서드

arr = np.random.randn(5, 4)
arr

array([[-0.9174451 , -1.24419728, -2.01999425,  0.82916801],
       [ 0.30591843,  0.14966882,  0.66318245, -0.43900741],
       [ 0.70788058, -0.85578757,  0.47875311, -1.58423868],
       [ 0.08842368,  0.13577186,  1.16927663,  0.16435561],
       [-0.36911017,  0.19927597, -0.25434641, -0.42167097]])

In [16]:
arr.mean(), np.mean(arr), arr.sum()

(-0.16070613427146638, -0.16070613427146638, -3.2141226854293277)

In [23]:
#column 의 평균
#arr.mean(0)
arr.mean(axis=0)

array([-0.03686651, -0.32305364,  0.00737431, -0.29027869])

In [24]:
#각 row의 mean을 계산하고, 배열로써 표기한다.
arr.mean(axis=1)

array([-0.83811716,  0.16994057, -0.31334814,  0.38945695, -0.2114629 ])

In [26]:
#모든 row의 합
arr.sum(0)


array([-0.18433257, -1.6152682 ,  0.03687153, -1.45139344])

In [31]:
#앞에있는 숫자까지의 합을 나타냄
arr =np.arange(8)
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [34]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [38]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
#각 배열에서의 cumulative product를 구해준다.
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

#### 4.3.3 불리언 배열을 위한 메서드

In [41]:

#양수인 배열 개수 구하기
arr = np.random.randn(100)
(arr>0).sum()

50

In [43]:
#any는 하나 이상의 값이 True, all 은 모든 원소가 True인지 검사

bools = np.array([False, False, True, False])
bools.any()

True

In [44]:
bools.all()

False

#### 4.3.4 정렬

In [46]:
arr = np.random.randn(5, 3)
arr

array([[-0.22049317, -0.43443773,  0.06566419],
       [ 0.36088095,  0.47606742,  0.18641321],
       [-0.97808649, -1.68421297, -0.29682046],
       [-0.59673339, -1.11208521, -0.54541459],
       [-1.60244167,  1.2440185 , -0.21758832]])

In [48]:
#1차원 부분 정렬
arr.sort(1)
arr

array([[-0.43443773, -0.22049317,  0.06566419],
       [ 0.18641321,  0.36088095,  0.47606742],
       [-1.68421297, -0.97808649, -0.29682046],
       [-1.11208521, -0.59673339, -0.54541459],
       [-1.60244167, -0.21758832,  1.2440185 ]])

In [50]:
#### 4.3.5 집합관련 함수
names = np.array(["Bob", "Joe", "Will", "Joe", "Will", "Joe", " Joe"])
#sorted(set(names))

np.unique(names)

array([' Joe', 'Bob', 'Joe', 'Will'], dtype='<U4')

In [ ]:
# unique(x)
# intersect1d(x, y) - 공통
# union1d(x, y) - 합집합
# in1d(x, y) - x의 원소가 y원소에 포함되는지 나타내는 Boolean
# setdiff1d(x, y) - x와 y의 차집합
