In [58]:
import numpy as np

In [64]:
data.shape

(2, 3)

In [65]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

In [68]:
data2 = [[1, 2, 3,4], [5, 6, 7, 8]]
arr2 = np.array(data2)

In [69]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [73]:
points = np.arange(-5, 5, 0.1)

In [74]:
points

array([-5.00000000e+00, -4.90000000e+00, -4.80000000e+00, -4.70000000e+00,
       -4.60000000e+00, -4.50000000e+00, -4.40000000e+00, -4.30000000e+00,
       -4.20000000e+00, -4.10000000e+00, -4.00000000e+00, -3.90000000e+00,
       -3.80000000e+00, -3.70000000e+00, -3.60000000e+00, -3.50000000e+00,
       -3.40000000e+00, -3.30000000e+00, -3.20000000e+00, -3.10000000e+00,
       -3.00000000e+00, -2.90000000e+00, -2.80000000e+00, -2.70000000e+00,
       -2.60000000e+00, -2.50000000e+00, -2.40000000e+00, -2.30000000e+00,
       -2.20000000e+00, -2.10000000e+00, -2.00000000e+00, -1.90000000e+00,
       -1.80000000e+00, -1.70000000e+00, -1.60000000e+00, -1.50000000e+00,
       -1.40000000e+00, -1.30000000e+00, -1.20000000e+00, -1.10000000e+00,
       -1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -1.77635684e-14,  1.00000000e-01,
        2.00000000e-01,  

In [75]:
data = [i**2 for i in range(1,11)]

In [76]:

len(data)

10

In [77]:
9 // 2

4

In [2]:
import numpy as np

In [3]:
np.load("some_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])